spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件大小

server:
  port: 9003

eureka:
    client:
      service-url:
        defaultZone: http://192.168.0.103:9000/eureka
    instance:
      prefer-ip-address: true
      ip-address: 192.168.0.103

fdfs:
  so-timeout: 2500     #读取超时时间
  connect-timeout: 600 #连接超时时间
  thumb-image:         #缩略图
    height: 60
    width: 60
  tracker-list:
    - 10.211.55.18:22122 #服务器配置列表

ly:
  upload:
    baseUrl: http://image.leyou.com:8080/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp